export const CarsBrands = {
  Coradir: "Coradir",
  VoltMotors: "Volt Motors",
  Chevrolet: "Chevrolet",
  Fiat: "Fiat",
  Ford: "Ford",
  Honda: "Honda",
  Hyundai: "Hyundai",
  Jeep: "Jeep",
  Kia: "Kia",
  Nissan: "Nissan",
  Peugeot: "Peugeot",
  Renault: "Renault",
  Toyota: "Toyota",
  Volkswagen: "Volkswagen",
  Citroen: "Citroën",
  DS: "DS Automobiles",
  BMW: "BMW",
  MercedesBenz: "Mercedes-Benz",
  Audi: "Audi",
  Mitsubishi: "Mitsubishi",
  Suzuki: "Suzuki",
  Chery: "Chery",
  Geely: "Geely",
  JAC: "JAC Motors",
  Baic: "BAIC",
  BYD: "BYD",
  Lifan: "Lifan",
  MG: "MG",
  Dodge: "Dodge",
  LandRover: "Land Rover",
  RangeRover: "Range Rover",
  Subaru: "Subaru",
  AlfaRomeo: "Alfa Romeo",
  Mini: "MINI",
  Porsche: "Porsche",
  Lexus: "Lexus",
  Volvo: "Volvo",
  Haval: "Haval",
  Isuzu: "Isuzu",
  Iveco: "Iveco",
  MAN: "MAN",
  DAF: "DAF",
  Kamaz: "Kamaz",
} as const

export type CarBrand = typeof CarsBrands[keyof typeof CarsBrands]